routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => ['auth','isAdmin']], function () {

    Route::get('/dashboard', function () {
        return view('admin.dashboard');
    });

});


Route::resource('posts', PostController::class);

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{

    protected $fillable = [
        'title', 'description','user_id','start_date','end_date','image'
    ];
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('auth')->except("index");
    }

    public function index()
    {
        try {
            if (Auth::user()) {
                $user_id = Auth::user()->id;
                if(Auth::user()->user_role == '1')
                {
                    $data = Post::latest()->paginate(5);
                }
                else
                {
                    $data = Post::where('user_id', $user_id)->paginate(5);
                }
            } else {
                $data = Post::latest()->paginate(5);
            }



            return view('posts.index',compact('data'))
                ->with('i', (request()->input('page', 1) - 1) * 5);
        } catch (\Exception $e) {
            $data = [
                'exception' => $e->getMessage()
            ];
            Log::info(json_encode($data));
            abort(500);
        }

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        try {
            return view('posts.create');
        } catch (\Exception $e) {
            $data = [
                'input_params' => $request->all(),

                'exception' => $e->getMessage()
            ];
            Log::info(json_encode($data));
            abort(500);
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            $request->validate([
                'title' => 'required',
                'description' => 'required',
                'start_date' => 'required',
                'end_date' => 'required',
            ]);

            $post = $request->all();
            $post['user_id']=Auth::user()->id;
            if($request->hasfile('image')){
                $file = $request->file('image');
                if($file){
                    $filename = time()."_".$file->getClientOriginalName();
                    $destinationPath = base_path().'/public/uploads/postimages' ;
                    $file->move($destinationPath,$filename);
                }
                $post['image']=$filename;
            }

            Post::create($post);

            return redirect()->route('posts.index')
                ->with('success','Post created successfully.');
        } catch (\Exception $e) {
            $data = [
                'input_params' => $request->all(),

                'exception' => $e->getMessage()
            ];
            Log::info(json_encode($data));
            abort(500);
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        try {
            return view('posts.show',compact('post'));

        } catch (\Exception $e) {
            $data = [
                'input_params' => $post->all(),

                'exception' => $e->getMessage()
            ];
            Log::info(json_encode($data));
            abort(500);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        try {
            return view('posts.edit',compact('post'));

        } catch (\Exception $e) {
            $data = [
                'input_params' => $post->all(),

                'exception' => $e->getMessage()
            ];
            Log::info(json_encode($data));
            abort(500);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        try {
            $request->validate([
                'title' => 'required',
                'description' => 'required',
                'start_date' => 'required',
                'end_date' => 'required',
            ]);
//        $post =  $request->all();
//        $post['user_id']=Auth::user()->id;
            $filename='';
            if($request->hasfile('image')){
                $file = $request->file('image');
                if($file){
                    $filename = time()."_".$file->getClientOriginalName();
                    $destinationPath = base_path().'/public/uploads/postimages' ;
                    $file->move($destinationPath,$filename);
                }
                $prev_path = base_path().'public/uploads/postimages'.$request->get('old_image');
                unlink($prev_path);
                $post['image'] = $filename;
            }else{
                $post['image']  = $request->get('old_image');
            }
//        echo "<pre>";
//        print_r($request->all());print_r($post->toArray());exit;
            $post->update($post->toArray());

            return redirect()->route('posts.index')
                ->with('success','Post updated successfully');
        } catch (\Exception $e) {
            $data = [
                'input_params' => $request->all(),

                'exception' => $e->getMessage()
            ];
            Log::info(json_encode($data));
            abort(500);
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        try {
            $post->delete();

            return redirect()->route('posts.index')
                ->with('success','Post deleted successfully');
        } catch (\Exception $e) {
            $data = [
                'input_params' => $post->all(),

                'exception' => $e->getMessage()
            ];
            Log::info(json_encode($data));
            abort(500);
        }

    }
}

resources/views/posts/create.blade.php
{{--@extends('posts.layout')--}}
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Add New Product</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('posts.index') }}"> Back</a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('posts.store') }}" id="postform" method="POST" enctype='multipart/form-data'>
        @csrf

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Title:</strong>
                    <input type="text" name="title" class="form-control" placeholder="Enter Title">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Description:</strong>
                    <textarea class="form-control" style="height:150px" name="description" placeholder="Enter Description"></textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Start Date:</strong>
                    <input id="start_date" type="date" class="form-control" name="start_date" placeholder="Enter Start date" required>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>End Date:</strong>
                    <input id="end_date" type="date" class="form-control" name="end_date" placeholder="Enter End date" required>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Image:</strong>
                    <input id="image" type="file" class="form-control" name="image" >
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>

    </form>
@endsection

resources/views/posts/edit.blade.php
{{--@extends('posts.layout')--}}
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Product</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('posts.index') }}"> Back</a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('posts.update',$post->id) }}" method="POST" id="postform" enctype='multipart/form-data'>
        @csrf
        @method('PUT')

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Title:</strong>
                    <input type="text" name="title" value="{{ $post->title }}" class="form-control" placeholder="Title">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Description:</strong>
                    <textarea class="form-control" style="height:150px" name="description" placeholder="Detail">{{ $post->description }}</textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Start Date:</strong>
                    <input id="start_date" type="date" class="form-control" name="start_date" placeholder="Enter Start date" value="{{ $post->start_date }}" required>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>End Date:</strong>
                    <input id="end_date" type="date" class="form-control" name="end_date" placeholder="Enter End date" value="{{ $post->end_date }}" required>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Image:</strong>
                    <input id="old_image" type="hidden1" class="form-control" name="old_image" value="{{$post->image}}" >

                    <div>
                        @if ($post->image)
                            <img class="image"  src="{{ URL::to('/') }}/uploads/postimages/{{$post->image}}">
                        @else
                            <img class="profile_image"  src="{{ URL::to('/') }}/uploads/images/noimg.png">
                        @endif
                    </div>
                    <input id="image" type="file" class="form-control" name="image"  >
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>

    </form>
@endsection

resources/views/posts/index.blade.php
{{--@extends('posts.layout')--}}
@extends('layouts.app')

@section('content')
    @guest
        <div class="row" style="margin-top: 5rem;">

        </div>
    @else
        <div class="row" style="margin-top: 5rem;">
            <div class="col-lg-12 margin-tb">
                <div class="pull-left">
                    <h2></h2>
                </div>
                <div class="pull-right">
                    <a class="btn btn-success" href="{{ route('posts.create') }}"> Create New Post</a>
                </div>
            </div>
        </div>
    @endguest


    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Name</th>
            <th>Details</th>
            <th>Start Date</th>
            <th>End Date</th>
            <th>Image</th>


            @guest

            @else
                <th width="280px">Action</th>
            @endguest
        </tr>
        @foreach ($data as $key => $value)
            <tr>
                <td>{{ ++$i }}</td>
                <td>{{ $value->title }}</td>
                <td>{{ \Str::limit($value->description, 100) }}</td>
                <td>{{ $value->start_date}}</td>
                <td>{{ $value->end_date}}</td>
                <td> @if ($value->image)
                        <img class="image"  src="{{ URL::to('/') }}/uploads/postimages/{{$value->image}}">
                    @else
                        <img class="profile_image"  src="{{ URL::to('/') }}/uploads/images/noimg.png">
                    @endif
                </td>

                    @guest

                    @else
                    <td>
                        <form action="{{ route('posts.destroy',$value->id) }}" method="POST">
                            <a class="btn btn-info" href="{{ route('posts.show',$value->id) }}">Show</a>
                            <a class="btn btn-primary" href="{{ route('posts.edit',$value->id) }}">Edit</a>
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    </td>
                    @endguest


            </tr>
        @endforeach
    </table>
    {!! $data->links() !!}
@endsection

resources/views/posts/layout.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Posts</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">
    <!-- Styles -->
    <style>
        html, body {
            background-color: #fff;
            color: #636b6f;
            font-family: 'Nunito', sans-serif;
            font-weight: 200;
            /*height: 100vh;*/
            margin: 0;
        }

        .full-height {
            /*height: 100vh;*/
        }

        .flex-center {
            align-items: center;
            display: flex;
            justify-content: center;
        }

        .position-ref {
            position: relative;
        }

        .top-right {
            position: absolute;
            right: 10px;
            top: 18px;
        }

        .content {
            text-align: center;
        }

        .title {
            font-size: 84px;
        }

        .links > a {
            color: #636b6f;
            padding: 0 25px;
            font-size: 13px;
            font-weight: 600;
            letter-spacing: .1rem;
            text-decoration: none;
            text-transform: uppercase;
        }

        .m-b-md {
            margin-bottom: 30px;
        }
    </style>
</head>
<body>
<div class="flex-center position-ref full-height">
    @if (Route::has('login'))
        <div class="top-right links">
            @auth
                <a href="{{ url('/home') }}">Home</a>
                <a href="{{ url('/posts') }}">post</a>
            @else
                <a href="{{ route('login') }}">Login</a>

                @if (Route::has('register'))
                    <a href="{{ route('register') }}">Register</a>
                @endif
            @endauth
        </div>
    @endif

</div>
<div class="container">
    @yield('content')
</div>

</body>
</html>

resources/views/posts/show.blade.php
{{--@extends('posts.layout')--}}
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show Product</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('posts.index') }}"> Back</a>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Title:</strong>
                {{ $post->title }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Description:</strong>
                {{ $post->description }}
            </div>
        </div>
    </div>
@endsection